# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for titan configurations
Name: jolla-configuration-titan
Requires:
- patterns-sailfish-device-configuration-titan

Summary: Jolla Configuration titan

