# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for titan configurations
Name: jolla-configuration-titan
Requires:
- pattern:jolla-hw-adaptation-titan
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# For devices with cellular modem. Those without one, please comment out:
- pattern:jolla-sailfish-cellular-apps
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools
<<<<<<< HEAD

- sailfish-content-graphics-z@ICON_RES@

# Multi-SIM settings
- jolla-settings-networking-multisim

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

=======
>>>>>>> 0944e0575ff31159fb8a9c199edf80d76e79bd73
# sd-utils for mounting sdcard
- sd-utils


Summary: Jolla Configuration titan

